/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewProject.java
 *
 * Created on May 9, 2011, 12:53:01 PM
 */

package com.searchkeyword.frame;

import com.searchkeyword.bean.RankTrackerBean;
import com.searchkeyword.common.CommonHelper;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Euphern_Java
 */
public class NewProject extends javax.swing.JFrame {

    RankTrackerBean rankTrackerBean=new RankTrackerBean();

    /** Creates new form NewProject */
    public NewProject() {
        initComponents();
        this.setTitle("Create New Project");
        CommonHelper.setScreenInCenter(this);
        CommonHelper.installCloseHandler(this);
    }



    public NewProject(RankTracker rankTracker) {
        initComponents();
        this.setTitle("Create New Project");
        CommonHelper.setScreenInCenter(this);
        CommonHelper.installCloseHandler(this);
        rankTrackerBean.setRankTracker(rankTracker);
//        if(rankTrackerBean!=null && rankTrackerBean.getWebsiteurl()!=null && !rankTrackerBean.getWebsiteurl().equals(""))
//        {
//            txtURL.setText(rankTrackerBean.getWebsiteurl());
//        }
    }

    
    
    public NewProject(RankTrackerBean rankTBean) {
        initComponents();
        this.setTitle("Create New Project");
        CommonHelper.setScreenInCenter(this);
        CommonHelper.installCloseHandler(this);
        rankTrackerBean=rankTBean;
        if(rankTrackerBean!=null && rankTrackerBean.getWebsiteurl()!=null && !rankTrackerBean.getWebsiteurl().equals(""))
        {
            txtURL.setText(rankTrackerBean.getWebsiteurl());
        }
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnHelp = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Enter Site URL to Check:");

        jLabel3.setText("Please enter the URL of the site you wish to track search engines ranking for.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleHelp(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleCancel(evt);
            }
        });

        btnFinish.setText("Finish");
        btnFinish.setEnabled(false);

        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleNext(evt);
            }
        });
        btnNext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                handleNextEnter(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHelp)
                    .addComponent(btnCancel)
                    .addComponent(btnFinish)
                    .addComponent(btnNext)
                    .addComponent(btnBack)))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/newprjMsg.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleNext(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleNext
        // TODO add your handling code here
       nextpage();
    }//GEN-LAST:event_handleNext

    private void handleHelp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleHelp
        // TODO add your handling code here:
        CommonHelper.openHelpURL();
    }//GEN-LAST:event_handleHelp

    private void handleCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleCancel
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_handleCancel

    private void handleNextEnter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_handleNextEnter
        // TODO add your handling code here:

        if(evt.getKeyCode()==10)
        {
            nextpage();
        }
        //System.out.println("Test  "+evt.getKeyCode());
    }//GEN-LAST:event_handleNextEnter


    private void nextpage()
    {
         if(txtURL.getText()!=null && !txtURL.getText().equals(""))
        {
            if(CommonHelper.checkURL(txtURL.getText()))
            {               
                rankTrackerBean.setWebsiteurl(txtURL.getText());
                  EnterKeyWord ek=new EnterKeyWord(rankTrackerBean);
                  ek.setVisible(true);
                  this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Invalid URL! Please enter the correct URL. ", "Invalid URL!", 0);
                txtURL.setFocusable(true);
            }
        }
        else{
             ImageIcon icon = new ImageIcon("/image/error.png");
            JOptionPane.showMessageDialog(rootPane, "The URL field is empty! Please enter the competitor's website URL. ", "The URL field is empty!", 0);
            txtURL.setFocusable(true);
        }
    }




    /**
    * @param args the command line arguments
    */
  /*  public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProject().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables

}
